name: WeatherApp
options:
  bundleIdPrefix: com.weather.app
  deploymentTarget:
    iOS: "15.0"
    tvOS: "15.0"
  xcodeVersion: "16.0"

settings:
  MARKETING_VERSION: "1.0"
  CURRENT_PROJECT_VERSION: "1"
  SWIFT_VERSION: "5.9"
  TARGETED_DEVICE_FAMILY: "1,2,3" # iPhone, iPad, Apple TV
  ASSETCATALOG_COMPILER_GLOBAL_ACCENT_COLOR_NAME: "Accent"
  ASSETCATALOG_COMPILER_GENERATE_SWIFT_ASSET_SYMBOL_EXTENSIONS: "YES"
  ENABLE_PREVIEWS: "YES"
  CODE_SIGN_STYLE: "Automatic"
  DEVELOPMENT_TEAM: "" # Add your team ID if needed

targets:
  WeatherApp:
    type: application
    platform: iOS
    deploymentTarget: "15.0"
    sources:
      - path: WeatherApp
        excludes:
          - "**/*.storyboard"
          - "**/*.xib"
    resources:
      - path: WeatherApp/Assets
    dependencies:
      - package: WeatherAPI
        path: WeatherAPI
      - package: WeatherUI
        path: WeatherUI
    info:
      path: WeatherApp/Info.plist
      properties:
        CFBundleDisplayName: "Weather App"
        CFBundleIdentifier: "com.weather.app.WeatherApp"
        UILaunchScreen: {}
        UISupportedInterfaceOrientations:
          - UIInterfaceOrientationPortrait
          - UIInterfaceOrientationLandscapeLeft
          - UIInterfaceOrientationLandscapeRight
        UISupportedInterfaceOrientations~ipad:
          - UIInterfaceOrientationPortrait
          - UIInterfaceOrientationPortraitUpsideDown
          - UIInterfaceOrientationLandscapeLeft
          - UIInterfaceOrientationLandscapeRight

  WeatherAppTV:
    type: application
    platform: tvOS
    deploymentTarget: "15.0"
    sources:
      - path: WeatherApp
        excludes:
          - "**/*.storyboard"
          - "**/*.xib"
          - "**/Info.plist"
    resources:
      - path: WeatherApp/Assets
    dependencies:
      - package: WeatherAPI
        path: WeatherAPI
      - package: WeatherUI
        path: WeatherUI
    info:
      path: WeatherApp/Info-tvOS.plist
      properties:
        CFBundleDisplayName: "Weather App TV"
        CFBundleIdentifier: "com.weather.app.WeatherAppTV"
        UISupportedInterfaceOrientations:
          - UIInterfaceOrientationLandscapeLeft
          - UIInterfaceOrientationLandscapeRight

packages:
  WeatherAPI:
    path: WeatherAPI
  WeatherUI:
    path: WeatherUI
